#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate compact, shared IANA offset tables (no host timezone dependency).

Requires tzdata==2026.3. Normal app builds use the checked-in result offline.
"""
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo
import tzdata

assert tzdata.__version__ == '2026.3'
root=Path(tzdata.__file__).parent/'zoneinfo'
start=int(datetime(2020,1,1,tzinfo=timezone.utc).timestamp())
end=int(datetime(2100,1,1,tzinfo=timezone.utc).timestamp())
names=(Path(tzdata.__file__).parent/'zones').read_text().splitlines()
groups={};zones=[]
for name in sorted(names):
    with (root/name).open('rb') as f: zone=ZoneInfo.from_file(f)
    def offset(epoch): return int(datetime.fromtimestamp(epoch,timezone.utc).astimezone(zone).utcoffset().total_seconds())
    previous=offset(start);entries=[(start,previous)]
    for epoch in range(start+86400,end,86400):
        current=offset(epoch)
        if current!=previous:
            lo,hi=epoch-86400,epoch
            while hi-lo>1:
                mid=(lo+hi)//2
                if offset(mid)==previous:lo=mid
                else:hi=mid
            entries.append((hi,current));previous=current
    key=tuple(entries)
    if key not in groups:groups[key]=len(groups)
    zones.append((name,groups[key]))
out=['// Generated by scripts/generate-timezones.py; IANA tzdata 2026c, public domain.',
     '// Supported UTC range: 2020-01-01 inclusive through 2100-01-01 exclusive.',
     'struct ZoneTransition {std::int64_t at;int offset;};']
for entries,index in groups.items():
    out.append('constexpr ZoneTransition Zone%d[]={%s};'%(index,','.join('{%dLL,%d}'%x for x in entries)))
out.append('struct Zone {const char* name;const ZoneTransition* entries;std::size_t count;};')
out.append('constexpr Zone Zones[]={')
for name,index in zones:out.append('{"%s",Zone%d,sizeof(Zone%d)/sizeof(ZoneTransition)},'%(name,index,index))
out.append('};')
target=Path(__file__).resolve().parents[1]/'src/timezones.inc'
target.write_text('\n'.join(out)+'\n',encoding='utf-8')
print(f'{len(zones)} IANA names, {len(groups)} shared tables, {target.stat().st_size} bytes')
